"""Authored content for DeepDelve's solo chronicle expansion."""

from __future__ import annotations

from typing import Any

CAMPAIGN_CHAPTERS: tuple[dict[str, Any], ...] = (
    {
        "key": "lantern_below",
        "number": 1,
        "name": "The Lantern Below",
        "emoji": "🏮",
        "floor": 1,
        "summary": "A dead delver arrives at Lastlight carrying a lantern that still whispers your name.",
        "scenes": (
            "At Lastlight's gate, the corpse of a missing surveyor grips a blue lantern. "
            "Its flame leans toward you despite the wind.",
            "Vesper identifies the lantern as one carried during the First Descent. Its base hides a map drawn in fresh ink.",
            "Beneath the Warrens, the map leads to a sealed watchroom. A voice behind the door asks "
            "whether Lastlight deserves the truth.",
        ),
        "choice": {
            "prompt": "What will guide your first descent?",
            "options": {
                "truth": ("Tell Lastlight everything", "Honesty opens allies—and dangerous attention."),
                "mercy": ("Hide the worst of it", "You protect the town, but carry the secret alone."),
                "power": ("Keep the lantern", "The flame answers ambition with a hungry warmth."),
            },
        },
        "reward": {"gold": 125, "xp": 90, "tokens": 1},
    },
    {
        "key": "silken_sky",
        "number": 2,
        "name": "The Silken Sky",
        "emoji": "🕸️",
        "floor": 6,
        "summary": "The stars beneath the Verdant Crypt begin to hatch.",
        "scenes": (
            "Black water shows constellations that do not exist above. One star blinks when you do.",
            "Orra forges a lens from crypt silk. Through it, every strand in Arachne's kingdom forms a map of Lastlight.",
            "In the drowned observatory, an unhatched star begs you not to return it to the sky.",
        ),
        "choice": {
            "prompt": "Decide the fate of the fallen star.",
            "options": {
                "free": ("Free the star", "Compassion may create a strange ally."),
                "seal": ("Seal it forever", "Lastlight's safety comes before unknowable life."),
                "harvest": ("Claim its fire", "Power taken from heaven always leaves a shadow."),
            },
        },
        "reward": {"gold": 250, "xp": 175, "tokens": 1},
    },
    {
        "key": "iron_dream",
        "number": 3,
        "name": "The Iron Dream",
        "emoji": "⚙️",
        "floor": 11,
        "summary": "The Cinder Foundry is manufacturing people who remember lives they never lived.",
        "scenes": (
            "An empty suit of armor calls you by a childhood name no one in Lastlight knows.",
            "The Foundry's memory press contains thousands of stolen lives, each stamped onto a metal leaf.",
            "Its ancient overseer offers to rebuild everyone the Deep has taken—if you restart the furnaces.",
        ),
        "choice": {
            "prompt": "What becomes of the memory forge?",
            "options": {
                "destroy": ("Break the press", "The dead remain dead, and their memories remain their own."),
                "preserve": ("Preserve the archive", "Knowledge survives, watched by those who fear it."),
                "ignite": ("Restart the forge", "Lastlight gains miracles made from stolen identity."),
            },
        },
        "reward": {"gold": 400, "xp": 280, "tokens": 2},
    },
    {
        "key": "hollow_name",
        "number": 4,
        "name": "The Hollow Name",
        "emoji": "👑",
        "floor": 16,
        "summary": "The Hollow King did not lose his name. He hid it inside Lastlight's oldest family.",
        "scenes": (
            "Every portrait in the Starless Court changes overnight to show your face beneath its crown.",
            "Rook discovers the royal bloodline survived above. The final heir has guarded Lastlight all along.",
            "At the black throne, the King's true name waits to be spoken, erased, or inherited.",
        ),
        "choice": {
            "prompt": "Finish the reign of the Hollow King.",
            "options": {
                "speak": ("Speak the true name", "Memory returns to the kingdom, including every crime."),
                "erase": ("Erase it forever", "The curse ends at the cost of a history no one can recover."),
                "inherit": ("Take the name", "You bind the crown to a living will—your own."),
            },
        },
        "reward": {"gold": 650, "xp": 425, "tokens": 2},
    },
    {
        "key": "fifth_bell",
        "number": 5,
        "name": "When the Fifth Bell Rings",
        "emoji": "🔔",
        "floor": 20,
        "summary": "The final warning bell sounds from beneath Lastlight, and the city answers.",
        "scenes": (
            "Four bells toll above. A fifth answers from far below, and every locked door in Lastlight opens.",
            "The Deep was never a prison under the city. Lastlight is the lock built inside the prison.",
            "At the Margin of the World, the architect of the dungeon offers one last bargain: descend, "
            "seal the way, or let the world learn what waits beneath it.",
        ),
        "choice": {
            "prompt": "Write the ending of the First Chronicle.",
            "options": {
                "descend": ("Become the Last Delver", "You pursue the source beyond every authored floor."),
                "seal": ("Become the Warden", "You bind the Deep and accept the burden of guarding it."),
                "reveal": ("Open the truth", "The age of solitary delvers ends; the world must choose together."),
            },
        },
        "reward": {"gold": 1000, "xp": 700, "tokens": 3},
    },
)

PUZZLES: tuple[dict[str, Any], ...] = (
    {
        "key": "three_statues",
        "name": "The Three Watchers",
        "emoji": "🗿",
        "min_floor": 1,
        "max_floor": 5,
        "text": (
            "Three statues face east, south, and west. A plaque reads: "
            "“I wake where the day is born, die where it is buried, and never look upon midnight.”"
        ),
        "options": {"east": "Turn the east statue", "south": "Turn the south statue", "west": "Turn the west statue"},
        "answer": "east",
        "success": "At sunrise",
        "hint": "The answer is a direction associated with sunrise.",
    },
    {
        "key": "first_bell_sequence",
        "name": "The Counting Bells",
        "emoji": "🔔",
        "min_floor": 1,
        "max_floor": 5,
        "text": (
            "Five tarnished bells ring in order: once, once, twice, three times, then five times. "
            "How many times must the sixth bell ring?"
        ),
        "options": {"six": "Six times", "seven": "Seven times", "eight": "Eight times"},
        "answer": "eight",
        "success": "Eight rings continue the sum",
        "hint": "Each count is made by adding the previous two counts.",
    },
    {
        "key": "young_candle",
        "name": "The Pilgrim's Candle",
        "emoji": "🕯️",
        "min_floor": 1,
        "max_floor": 5,
        "text": "A wax face whispers: “I stand tall when young and grow short as I age. What am I?”",
        "options": {"candle": "A candle", "shadow": "A shadow", "tree": "A tree"},
        "answer": "candle",
        "success": "A candle",
        "hint": "Its life is measured by how long it provides light.",
    },
    {
        "key": "noon_arches",
        "name": "The Sundial Arches",
        "emoji": "☀️",
        "min_floor": 1,
        "max_floor": 5,
        "text": (
            "Three stone arches cast shadows across a sundial. The mechanism asks which shadow marks the sun "
            "at its highest point."
        ),
        "options": {"longest": "The longest shadow", "shortest": "The shortest shadow", "west": "The western shadow"},
        "answer": "shortest",
        "success": "The shortest shadow marks noon",
        "hint": "A high light source casts a shorter shadow.",
    },
    {
        "key": "footsteps_taken",
        "name": "The Borrowed Footsteps",
        "emoji": "👣",
        "min_floor": 1,
        "max_floor": 5,
        "text": "A door asks: “The more of me you take, the more you leave behind. What am I?”",
        "options": {"coins": "Coins", "footsteps": "Footsteps", "memories": "Memories"},
        "answer": "footsteps",
        "success": "Footsteps",
        "hint": "Taking these requires walking away from where they remain.",
    },
    {
        "key": "mushroom_chorus",
        "name": "The Spore Choir",
        "emoji": "🍄",
        "min_floor": 6,
        "max_floor": 10,
        "text": ("Four caps sing in a loop: blue, red, violet, blue, red… Only the next voice will open the root-bound gate."),
        "options": {"blue": "Touch blue", "red": "Touch red", "violet": "Touch violet"},
        "answer": "violet",
        "success": "The third voice",
        "hint": "Listen for a repeating sequence of three.",
    },
    {
        "key": "root_doubling",
        "name": "The Doubling Roots",
        "emoji": "🌱",
        "min_floor": 6,
        "max_floor": 10,
        "text": (
            "Glowing roots divide across four tiles: two strands, four, eight, then sixteen. "
            "How many strands belong on the fifth tile?"
        ),
        "options": {"twenty": "Twenty", "twenty_four": "Twenty-four", "thirty_two": "Thirty-two"},
        "answer": "thirty_two",
        "success": "Thirty-two strands",
        "hint": "Each tile has twice as many strands as the previous tile.",
    },
    {
        "key": "ordered_caps",
        "name": "The Cap Procession",
        "emoji": "🍄",
        "min_floor": 6,
        "max_floor": 10,
        "text": (
            "A red mushroom stands left of a blue mushroom. A violet mushroom stands right of the blue one. "
            "Which color occupies the middle?"
        ),
        "options": {"red": "Red", "blue": "Blue", "violet": "Violet"},
        "answer": "blue",
        "success": "Blue stands between red and violet",
        "hint": "Place the mushrooms from left to right using both statements.",
    },
    {
        "key": "echo_intervals",
        "name": "The Patient Echo",
        "emoji": "🗣️",
        "min_floor": 6,
        "max_floor": 10,
        "text": (
            "A cavern answers four calls after two, four, six, and eight heartbeats. "
            "After how many heartbeats will it answer the fifth call?"
        ),
        "options": {"nine": "Nine", "ten": "Ten", "twelve": "Twelve"},
        "answer": "ten",
        "success": "Ten heartbeats",
        "hint": "The delay increases by two each time.",
    },
    {
        "key": "spore_family",
        "name": "The Spore Lineage",
        "emoji": "🦠",
        "min_floor": 6,
        "max_floor": 10,
        "text": (
            "One spore becomes two at the first bell. Every spore divides in two at each later bell. "
            "How many spores exist immediately after the fourth bell?"
        ),
        "options": {"eight": "Eight", "twelve": "Twelve", "sixteen": "Sixteen"},
        "answer": "sixteen",
        "success": "Sixteen spores",
        "hint": "The population after each bell is 2, 4, 8, then…",
    },
    {
        "key": "foundry_weight",
        "name": "The Foundry Balance",
        "emoji": "⚖️",
        "min_floor": 11,
        "max_floor": 15,
        "text": (
            "A brass scale holds two iron ingots and one ember on the left. "
            "The right holds one ingot and three embers. It balances. Which weighs more?"
        ),
        "options": {"iron": "An iron ingot", "ember": "A living ember", "equal": "They are equal"},
        "answer": "ember",
        "success": "The living ember",
        "hint": "Remove one ingot and one ember from both sides, then compare what remains.",
    },
    {
        "key": "three_gears",
        "name": "The Three-Gear Lock",
        "emoji": "⚙️",
        "min_floor": 11,
        "max_floor": 15,
        "text": (
            "Gear A turns clockwise and drives Gear B. Gear B drives Gear C. "
            "Which direction does Gear C turn?"
        ),
        "options": {"clockwise": "Clockwise", "counter": "Counterclockwise", "still": "It remains still"},
        "answer": "clockwise",
        "success": "Clockwise after two reversals",
        "hint": "Each touching pair of gears reverses direction.",
    },
    {
        "key": "hammer_differences",
        "name": "The Smith's Rhythm",
        "emoji": "🔨",
        "min_floor": 11,
        "max_floor": 15,
        "text": (
            "A memory-smith strikes an anvil 2, 3, 5, 8, then 12 times. "
            "How many strikes complete the next phrase?"
        ),
        "options": {"fifteen": "Fifteen", "sixteen": "Sixteen", "seventeen": "Seventeen"},
        "answer": "seventeen",
        "success": "Seventeen strikes",
        "hint": "The increases are one, two, three, four, and then five.",
    },
    {
        "key": "one_true_forge",
        "name": "The Honest Furnace",
        "emoji": "🔥",
        "min_floor": 11,
        "max_floor": 15,
        "text": (
            "Exactly one inscription is true. Iron says, ‘The safe door is not iron.’ Bronze says, "
            "‘The safe door is silver.’ Silver says, ‘Bronze lies.’ Which door is safe?"
        ),
        "options": {"iron": "The iron door", "bronze": "The bronze door", "silver": "The silver door"},
        "answer": "iron",
        "success": "The iron door leaves exactly one truth",
        "hint": "Test each door and count how many inscriptions would be true.",
    },
    {
        "key": "furnace_hunger",
        "name": "The Hungry Furnace",
        "emoji": "🔥",
        "min_floor": 11,
        "max_floor": 15,
        "text": "The cold furnace asks: “Feed me wood and I live; give me water and I die. What am I?”",
        "options": {"fire": "Fire", "iron": "Iron", "steam": "Steam"},
        "answer": "fire",
        "success": "Fire",
        "hint": "It consumes fuel but cannot survive being doused.",
    },
    {
        "key": "mirror_court",
        "name": "The Courtiers' Mirrors",
        "emoji": "🪞",
        "min_floor": 16,
        "max_floor": 20,
        "text": (
            "One mirror always lies, one always tells the truth, and one repeats your belief. "
            "The truthful mirror says, “The silver door is safe.” Which door do you take?"
        ),
        "options": {"silver": "The silver door", "black": "The black door", "mirror": "Step through the mirror"},
        "answer": "silver",
        "success": "Trust the known truth",
        "hint": "You have already been told which speaker is truthful.",
    },
    {
        "key": "mirrored_live",
        "name": "The Reversed Testament",
        "emoji": "🪞",
        "min_floor": 16,
        "max_floor": 20,
        "text": "The word LIVE is carved so that it can only be read in a mirror. What word appears in the glass?",
        "options": {"veil": "VEIL", "evil": "EVIL", "life": "LIFE"},
        "answer": "evil",
        "success": "EVIL",
        "hint": "Reverse the order of all four letters.",
    },
    {
        "key": "one_truth_mask",
        "name": "The Masked Testimony",
        "emoji": "🎭",
        "min_floor": 16,
        "max_floor": 20,
        "text": (
            "Exactly two masks speak truth. Gold says, ‘Silver is safe.’ Silver says, ‘Gold is lying.’ "
            "Black says, ‘Silver is lying.’ Which mask is safe?"
        ),
        "options": {"gold": "Gold", "silver": "Silver", "black": "Black"},
        "answer": "silver",
        "success": "Silver makes only Gold's claim true",
        "hint": "Assume each mask is safe in turn, then find the case with two true statements.",
    },
    {
        "key": "royal_ages",
        "name": "The Portrait Succession",
        "emoji": "🖼️",
        "min_floor": 16,
        "max_floor": 20,
        "text": (
            "The duke is older than the queen. The queen is older than the heir. "
            "Whose portrait belongs between the other two?"
        ),
        "options": {"duke": "The duke", "queen": "The queen", "heir": "The heir"},
        "answer": "queen",
        "success": "The queen is the middle generation",
        "hint": "Arrange all three from oldest to youngest.",
    },
    {
        "key": "court_clock",
        "name": "The Court's Clock",
        "emoji": "🕰️",
        "min_floor": 16,
        "max_floor": 20,
        "text": (
            "A clock strikes once at the first hour, twice at the second, and three times at the third. "
            "How many total strikes have sounded by the end of the fourth hour?"
        ),
        "options": {"seven": "Seven", "ten": "Ten", "twelve": "Twelve"},
        "answer": "ten",
        "success": "Ten total strikes",
        "hint": "Add the strikes from all four hours: 1 + 2 + 3 + 4.",
    },
    {
        "key": "unwritten_word",
        "name": "A Word Without Letters",
        "emoji": "🌀",
        "min_floor": 21,
        "max_floor": 999,
        "text": ("A door asks: “What becomes larger the more you remove from it?” Three answers form in the air."),
        "options": {"wound": "A wound", "hole": "A hole", "memory": "A memory"},
        "answer": "hole",
        "success": "A hole",
        "hint": "Think of empty space created by taking material away.",
    },
    {
        "key": "tomorrow_door",
        "name": "The Door of Tomorrow",
        "emoji": "⏳",
        "min_floor": 21,
        "max_floor": 999,
        "text": "An unborn voice asks: “I am always approaching, but I never arrive. What am I?”",
        "options": {"tomorrow": "Tomorrow", "death": "Death", "sunrise": "Sunrise"},
        "answer": "tomorrow",
        "success": "Tomorrow",
        "hint": "Once it arrives, it has a different name.",
    },
    {
        "key": "named_silence",
        "name": "The Quiet Name",
        "emoji": "🤫",
        "min_floor": 21,
        "max_floor": 999,
        "text": "Letters appear without sound: “Speak my name and you destroy me. What am I?”",
        "options": {"silence": "Silence", "secret": "A secret", "darkness": "Darkness"},
        "answer": "silence",
        "success": "Silence",
        "hint": "The act of answering aloud ends the thing being described.",
    },
    {
        "key": "void_doubling",
        "name": "The Expanding Void",
        "emoji": "🌌",
        "min_floor": 21,
        "max_floor": 999,
        "text": "Stars ignite in groups of one, two, four, and eight. How many ignite in the next darkness?",
        "options": {"twelve": "Twelve", "sixteen": "Sixteen", "thirty_two": "Thirty-two"},
        "answer": "sixteen",
        "success": "Sixteen stars",
        "hint": "Each group is twice the size of the one before it.",
    },
    {
        "key": "memory_book",
        "name": "The Book That Remembers",
        "emoji": "📖",
        "min_floor": 21,
        "max_floor": 999,
        "text": (
            "A sealed object says: “I hold countless voices but never speak, and preserve the dead without graves. "
            "What am I?”"
        ),
        "options": {"book": "A book", "mirror": "A mirror", "bell": "A bell"},
        "answer": "book",
        "success": "A book",
        "hint": "Its voices are read, and its dead live as written memories.",
    },
)

# A second authored set doubles each floor band's variety. Keeping these in a
# separate tuple makes it easy to audit the original and expansion pools.
PUZZLES += (
    {
        "key": "borrowed_name",
        "name": "The Familiar Whisper",
        "emoji": "💬",
        "min_floor": 1,
        "max_floor": 5,
        "text": "A whisper asks: “What belongs to you, but other people use it more often than you do?”",
        "options": {"name": "Your name", "lantern": "Your lantern", "shadow": "Your shadow"},
        "answer": "name",
        "success": "Your name",
        "hint": "People use it when they address you.",
    },
    {
        "key": "moon_pool",
        "name": "The Moon Below",
        "emoji": "🌙",
        "min_floor": 1,
        "max_floor": 5,
        "text": "A silver moon lies at the bottom of a pool, yet it is never wet. What are you seeing?",
        "options": {"coin": "A silver coin", "reflection": "A reflection", "fish": "A pale fish"},
        "answer": "reflection",
        "success": "The moon's reflection",
        "hint": "Look at the surface rather than the bottom.",
    },
    {
        "key": "lanterns_remaining",
        "name": "The Patient Lanterns",
        "emoji": "🏮",
        "min_floor": 1,
        "max_floor": 5,
        "text": "Three lanterns hang from a beam. You extinguish one. How many lanterns remain hanging?",
        "options": {"two": "Two", "three": "Three", "none": "None"},
        "answer": "three",
        "success": "All three remain",
        "hint": "Extinguishing a lantern does not remove it.",
    },
    {
        "key": "stair_steps",
        "name": "The Numbered Stair",
        "emoji": "🪜",
        "min_floor": 1,
        "max_floor": 5,
        "text": "The first four steps read 2, 4, 6, and 8. Which number opens the fifth step?",
        "options": {"nine": "Nine", "ten": "Ten", "twelve": "Twelve"},
        "answer": "ten",
        "success": "Ten continues the even numbers",
        "hint": "Each step adds two.",
    },
    {
        "key": "smallest_key",
        "name": "The Three Keys",
        "emoji": "🗝️",
        "min_floor": 1,
        "max_floor": 5,
        "text": "The iron key is heavier than the copper key. The copper key is heavier than the bone key. Which is lightest?",
        "options": {"iron": "Iron", "copper": "Copper", "bone": "Bone"},
        "answer": "bone",
        "success": "The bone key is lightest",
        "hint": "Put the keys in order from heaviest to lightest.",
    },
    {
        "key": "river_bed",
        "name": "The Sleepless River",
        "emoji": "🌊",
        "min_floor": 6,
        "max_floor": 10,
        "text": "What has a bed but never sleeps, and a mouth but never eats?",
        "options": {"river": "A river", "cave": "A cave", "wolf": "A wolf"},
        "answer": "river",
        "success": "A river",
        "hint": "Its mouth empties into a larger body of water.",
    },
    {
        "key": "alternating_spores",
        "name": "The Two-Tone Spores",
        "emoji": "🦠",
        "min_floor": 6,
        "max_floor": 10,
        "text": "Spores flash green, violet, green, violet, green. Which color flashes next?",
        "options": {"green": "Green", "violet": "Violet", "blue": "Blue"},
        "answer": "violet",
        "success": "Violet continues the alternating pattern",
        "hint": "The two colors take turns.",
    },
    {
        "key": "web_spokes",
        "name": "The Spider's Count",
        "emoji": "🕸️",
        "min_floor": 6,
        "max_floor": 10,
        "text": "A web has eight straight spokes. The spider snaps three of them. How many unbroken spokes remain?",
        "options": {"three": "Three", "five": "Five", "six": "Six"},
        "answer": "five",
        "success": "Five spokes remain",
        "hint": "Subtract the broken spokes from the original eight.",
    },
    {
        "key": "root_height",
        "name": "The Rootbound Trio",
        "emoji": "🌳",
        "min_floor": 6,
        "max_floor": 10,
        "text": "The red root is taller than blue. Blue is taller than white. Which root is shortest?",
        "options": {"red": "Red", "blue": "Blue", "white": "White"},
        "answer": "white",
        "success": "The white root is shortest",
        "hint": "Arrange the roots from tallest to shortest.",
    },
    {
        "key": "mushroom_hours",
        "name": "The Fungal Clock",
        "emoji": "🍄",
        "min_floor": 6,
        "max_floor": 10,
        "text": "Caps open at the third, sixth, ninth, and twelfth chimes. At which chime does the next cap open?",
        "options": {"thirteen": "Thirteen", "fifteen": "Fifteen", "eighteen": "Eighteen"},
        "answer": "fifteen",
        "success": "The fifteenth chime",
        "hint": "The chime count rises by three.",
    },
    {
        "key": "coal_life",
        "name": "The Smith's Fuel",
        "emoji": "⚫",
        "min_floor": 11,
        "max_floor": 15,
        "text": "I am black when bought, red while used, and gray when discarded. What am I?",
        "options": {"coal": "Coal", "iron": "Iron", "oil": "Oil"},
        "answer": "coal",
        "success": "Coal",
        "hint": "It glows as it burns and ends as ash.",
    },
    {
        "key": "foundry_heat",
        "name": "The Rising Furnace",
        "emoji": "🌡️",
        "min_floor": 11,
        "max_floor": 15,
        "text": "The furnace gauge climbs 100, 200, 300, 400. Which mark comes next?",
        "options": {"450": "450", "500": "500", "600": "600"},
        "answer": "500",
        "success": "The 500 mark",
        "hint": "Each reading increases by one hundred.",
    },
    {
        "key": "forge_procession",
        "name": "The Forge Procession",
        "emoji": "⚒️",
        "min_floor": 11,
        "max_floor": 15,
        "text": "Tongs hang left of the hammer. The hammer hangs left of the chisel. Which tool hangs in the middle?",
        "options": {"tongs": "Tongs", "hammer": "Hammer", "chisel": "Chisel"},
        "answer": "hammer",
        "success": "The hammer hangs in the middle",
        "hint": "Place all three tools from left to right.",
    },
    {
        "key": "anvil_echoes",
        "name": "The Doubling Anvil",
        "emoji": "🔨",
        "min_floor": 11,
        "max_floor": 15,
        "text": "The anvil echoes once, twice, four times, then eight times. How many echoes follow?",
        "options": {"twelve": "Twelve", "sixteen": "Sixteen", "twenty": "Twenty"},
        "answer": "sixteen",
        "success": "Sixteen echoes",
        "hint": "Each echo count doubles.",
    },
    {
        "key": "balanced_blades",
        "name": "The Equal Blades",
        "emoji": "⚖️",
        "min_floor": 11,
        "max_floor": 15,
        "text": "Two identical swords balance six identical daggers. One sword weighs the same as how many daggers?",
        "options": {"two": "Two", "three": "Three", "six": "Six"},
        "answer": "three",
        "success": "Three daggers",
        "hint": "Divide both sides of the balance by two.",
    },
    {
        "key": "shadow_noon",
        "name": "The Courtly Shadow",
        "emoji": "🌞",
        "min_floor": 16,
        "max_floor": 20,
        "text": "At noon, the palace sundial casts its shortest shadow. At sunset, is its shadow shorter or longer?",
        "options": {"shorter": "Shorter", "longer": "Longer", "same": "The same"},
        "answer": "longer",
        "success": "The sunset shadow is longer",
        "hint": "A low sun stretches shadows.",
    },
    {
        "key": "crown_weight",
        "name": "The Weight of Crowns",
        "emoji": "👑",
        "min_floor": 16,
        "max_floor": 20,
        "text": "The gold crown is heavier than silver. Silver is heavier than glass. Which crown is heaviest?",
        "options": {"gold": "Gold", "silver": "Silver", "glass": "Glass"},
        "answer": "gold",
        "success": "The gold crown is heaviest",
        "hint": "Follow the comparisons from greatest to least.",
    },
    {
        "key": "mask_colors",
        "name": "The Masquerade Waltz",
        "emoji": "🎭",
        "min_floor": 16,
        "max_floor": 20,
        "text": "Masks pass in order: black, gold, white, black, gold. Which mask comes next?",
        "options": {"black": "Black", "gold": "Gold", "white": "White"},
        "answer": "white",
        "success": "White completes the repeating trio",
        "hint": "The colors repeat in groups of three.",
    },
    {
        "key": "heir_seats",
        "name": "The Empty Throne",
        "emoji": "🪑",
        "min_floor": 16,
        "max_floor": 20,
        "text": "The queen sits left of the heir. The regent sits right of the heir. Who occupies the center seat?",
        "options": {"queen": "The queen", "heir": "The heir", "regent": "The regent"},
        "answer": "heir",
        "success": "The heir sits in the center",
        "hint": "Place the heir between the other two nobles.",
    },
    {
        "key": "royal_coins",
        "name": "The Treasurer's Seal",
        "emoji": "🪙",
        "min_floor": 16,
        "max_floor": 20,
        "text": "Four royal purses each hold three coins. How many coins do they hold altogether?",
        "options": {"seven": "Seven", "twelve": "Twelve", "sixteen": "Sixteen"},
        "answer": "twelve",
        "success": "Twelve coins",
        "hint": "Multiply four purses by three coins.",
    },
    {
        "key": "room_of_light",
        "name": "The Weightless Guest",
        "emoji": "💡",
        "min_floor": 21,
        "max_floor": 999,
        "text": "What can fill an entire chamber without taking up any space?",
        "options": {"light": "Light", "water": "Water", "smoke": "Smoke"},
        "answer": "light",
        "success": "Light",
        "hint": "It lets you see the chamber but has no volume.",
    },
    {
        "key": "corner_traveler",
        "name": "The Far-Traveled Corner",
        "emoji": "✉️",
        "min_floor": 21,
        "max_floor": 999,
        "text": "What travels around the world while remaining in one corner?",
        "options": {"stamp": "A postage stamp", "shadow": "A shadow", "compass": "A compass"},
        "answer": "stamp",
        "success": "A postage stamp",
        "hint": "It rides on the corner of an envelope.",
    },
    {
        "key": "minute_moment",
        "name": "The Letter Between Seconds",
        "emoji": "⌛",
        "min_floor": 21,
        "max_floor": 999,
        "text": "What appears once in a minute, twice in a moment, and never in a thousand years?",
        "options": {"letter_m": "The letter M", "second": "A second", "memory": "A memory"},
        "answer": "letter_m",
        "success": "The letter M",
        "hint": "Study the written words, not their lengths of time.",
    },
    {
        "key": "bodiless_reply",
        "name": "The Unseen Reply",
        "emoji": "🗣️",
        "min_floor": 21,
        "max_floor": 999,
        "text": "What speaks without a mouth and answers without ears?",
        "options": {"echo": "An echo", "book": "A book", "ghost": "A ghost"},
        "answer": "echo",
        "success": "An echo",
        "hint": "It returns the sound you send into an empty place.",
    },
    {
        "key": "void_triangles",
        "name": "The Triangular Void",
        "emoji": "🔺",
        "min_floor": 21,
        "max_floor": 999,
        "text": "Marks gather in groups of 1, 3, 6, and 10. How many marks form the next group?",
        "options": {"twelve": "Twelve", "fifteen": "Fifteen", "twenty": "Twenty"},
        "answer": "fifteen",
        "success": "Fifteen marks",
        "hint": "The increases are two, three, four, and then five.",
    },
)

COMPANIONS: dict[str, dict[str, Any]] = {
    "brindle": {
        "name": "Brindle",
        "emoji": "🐕",
        "role": "Warren Hound",
        "unlock_floor": 3,
        "description": "A scarred tunnel hound who finds traps before they find you.",
        "passive": "10% trap avoidance and improved material finds.",
        "bond_lines": (
            "Brindle watches every dark passage, but keeps one ear turned toward you.",
            "Brindle has learned the sound of your fear and quietly stands closer.",
            "No path is too dark while Brindle can still find your trail home.",
        ),
        "attack": 3,
        "defense": 0,
        "luck": 2,
    },
    "mote": {
        "name": "Mote",
        "emoji": "🧚",
        "role": "Spore Wisp",
        "unlock_floor": 8,
        "description": "A glowing mote born from a fallen star's dream.",
        "passive": "Restores mana after battle and improves puzzle rewards.",
        "bond_lines": (
            "Mote imitates the rhythm of your lantern with shy pulses of light.",
            "Mote paints tiny constellations in the air whenever you make camp.",
            "Mote no longer calls the sky home. Home is wherever your lantern stops.",
        ),
        "attack": 2,
        "defense": 0,
        "luck": 3,
    },
    "clank": {
        "name": "Clank",
        "emoji": "🤖",
        "role": "Memory Automaton",
        "unlock_floor": 13,
        "description": "A tiny foundry construct with the manners of a forgotten knight.",
        "passive": "Adds defense and occasionally finds extra crafting materials.",
        "bond_lines": (
            "Clank salutes before every door, including doors you just exited.",
            "Clank remembers fragments of knighthood and insists on polishing your armor.",
            "Clank has recovered one complete memory: choosing to follow you.",
        ),
        "attack": 1,
        "defense": 3,
        "luck": 0,
    },
    "nocturne": {
        "name": "Nocturne",
        "emoji": "🦇",
        "role": "Court Familiar",
        "unlock_floor": 18,
        "description": "A royal bat who insists it is merely between kingdoms.",
        "passive": "Improves critical chance and softens elite enemies.",
        "bond_lines": (
            "Nocturne claims your shoulder is merely a strategically superior perch.",
            "Nocturne has begun referring to your camp as the temporary royal court.",
            "Nocturne offers you its broken crown. Apparently the abdication is permanent.",
        ),
        "attack": 3,
        "defense": 1,
        "luck": 2,
    },
    "echo": {
        "name": "Echo",
        "emoji": "🌌",
        "role": "Unwritten Shade",
        "unlock_floor": 23,
        "description": "Your shadow from a future expedition that never happened.",
        "passive": "Amplifies all stats and sometimes preserves an exploration turn.",
        "bond_lines": (
            "Echo moves a heartbeat before you do, then pretends not to notice.",
            "Echo remembers victories you have not achieved and mourns deaths you avoided.",
            "For the first time, Echo casts a shadow of its own beside yours.",
        ),
        "attack": 3,
        "defense": 2,
        "luck": 3,
    },
}

PROFESSIONS: dict[str, dict[str, Any]] = {
    "blacksmith": {
        "name": "Blacksmith",
        "emoji": "⚒️",
        "description": "Master equipment, upgrades, and the tempering of impossible metals.",
        "benefit": "Cheaper crafting; crafted items gain bonus upgrade levels.",
    },
    "alchemist": {
        "name": "Alchemist",
        "emoji": "⚗️",
        "description": "Distill dungeon matter into potions, tonics, and volatile solutions.",
        "benefit": "Cheaper potions; chance to brew a bonus potion after gathering.",
    },
    "cartographer": {
        "name": "Cartographer",
        "emoji": "🗺️",
        "description": "Read the Deep's shifting geometry and record paths that should not exist.",
        "benefit": "More daily turns; increased puzzle and exploration rewards.",
    },
    "relic_hunter": {
        "name": "Relic Hunter",
        "emoji": "🏺",
        "description": "Recover, identify, and profit from the artifacts of vanished civilizations.",
        "benefit": "Better treasure rarity and additional arcane shards.",
    },
}

TOWN_BUILDINGS: dict[str, dict[str, Any]] = {
    "forge": {
        "name": "Deepforge",
        "emoji": "⚒️",
        "description": "Reduces crafting costs and improves crafted equipment.",
        "costs": (500, 1400, 3200, 7000),
    },
    "infirmary": {
        "name": "Lantern Infirmary",
        "emoji": "🏥",
        "description": "Reduces rest prices and strengthens healing potions.",
        "costs": (450, 1250, 2900, 6500),
    },
    "archive": {
        "name": "Forbidden Archive",
        "emoji": "📚",
        "description": "Improves lore, puzzle, and campaign rewards.",
        "costs": (600, 1600, 3600, 8000),
    },
    "watch": {
        "name": "Lastlight Watch",
        "emoji": "🛡️",
        "description": "Weakens dangerous events and grants more daily turns.",
        "costs": (550, 1500, 3400, 7600),
    },
}

WORLD_EVENTS: tuple[dict[str, Any], ...] = (
    {
        "key": "black_rain",
        "name": "The Black Rain",
        "emoji": "🌧️",
        "description": "Ink-dark rain falls upward from the dungeon. Enemies grow fierce, but leave richer spoils.",
        "combat": 1.15,
        "reward": 1.35,
        "puzzle": 1.0,
    },
    {
        "key": "lantern_festival",
        "name": "Festival of Last Light",
        "emoji": "🏮",
        "description": "The outpost burns a thousand blue lanterns. Services are cheaper and spirits run high.",
        "combat": 0.95,
        "reward": 1.1,
        "puzzle": 1.1,
    },
    {
        "key": "shifting_stairs",
        "name": "The Shifting Stairs",
        "emoji": "🪜",
        "description": "Passages rearrange by the hour, exposing puzzles and forgotten caches.",
        "combat": 1.0,
        "reward": 1.2,
        "puzzle": 1.65,
    },
    {
        "key": "hollow_march",
        "name": "The Hollow March",
        "emoji": "👑",
        "description": "A dead procession climbs toward Lastlight. Elite enemies are common and unusually vulnerable.",
        "combat": 1.1,
        "reward": 1.5,
        "puzzle": 0.9,
    },
    {
        "key": "quiet_deep",
        "name": "The Quiet Deep",
        "emoji": "🤫",
        "description": "For one day, the dungeon stops whispering. Explorers recover quickly, but treasure grows scarce.",
        "combat": 0.85,
        "reward": 0.9,
        "puzzle": 1.2,
    },
)

EXTENDED_ENEMIES: tuple[dict[str, Any], ...] = (
    {"name": "Lantern Thief", "emoji": "🕯️", "tier": 1, "hp": 40, "attack": 10, "defense": 2, "gold": 16, "xp": 17},
    {"name": "Gravebound Pilgrim", "emoji": "⛓️", "tier": 1, "hp": 51, "attack": 8, "defense": 5, "gold": 14, "xp": 18},
    {"name": "Spore Oracle", "emoji": "🔮", "tier": 2, "hp": 62, "attack": 15, "defense": 3, "gold": 25, "xp": 27},
    {"name": "Thorn Matriarch", "emoji": "🌹", "tier": 2, "hp": 88, "attack": 13, "defense": 7, "gold": 29, "xp": 31},
    {"name": "Memory Smith", "emoji": "🔨", "tier": 3, "hp": 108, "attack": 21, "defense": 9, "gold": 46, "xp": 48},
    {"name": "Cinder Seraph", "emoji": "🪽", "tier": 3, "hp": 98, "attack": 25, "defense": 6, "gold": 50, "xp": 52},
    {"name": "Nameless Duke", "emoji": "🎭", "tier": 4, "hp": 148, "attack": 29, "defense": 12, "gold": 72, "xp": 75},
    {"name": "Black Sun Priest", "emoji": "🌘", "tier": 4, "hp": 135, "attack": 33, "defense": 8, "gold": 78, "xp": 81},
    {"name": "Sentence Eater", "emoji": "📖", "tier": 5, "hp": 195, "attack": 37, "defense": 13, "gold": 96, "xp": 101},
    {"name": "Yesterday's Corpse", "emoji": "⌛", "tier": 5, "hp": 220, "attack": 35, "defense": 16, "gold": 105, "xp": 110},
)

EXTENDED_BOSSES: tuple[dict[str, Any], ...] = (
    {
        "name": "The Gaoler of Hours",
        "emoji": "⏰",
        "description": "Every strike ages your shadow while the thing inside the clock screams backward.",
        "hp": 680,
        "attack": 46,
        "defense": 23,
        "gold": 720,
        "xp": 760,
    },
    {
        "name": "Saint Caligo, Unremembered",
        "emoji": "🪽",
        "description": "A halo of erased names burns around the saint who was removed from every prayer.",
        "hp": 850,
        "attack": 53,
        "defense": 27,
        "gold": 900,
        "xp": 940,
    },
    {
        "name": "The Author Beneath",
        "emoji": "✒️",
        "description": "It lifts its pen. The room becomes a sentence, and you become the final word.",
        "hp": 1100,
        "attack": 61,
        "defense": 31,
        "gold": 1250,
        "xp": 1300,
    },
)
