"""Authored Origins & Armory content for DeepDelve."""

from __future__ import annotations

from typing import Any

STARTER_WEAPONS: dict[str, dict[str, dict[str, Any]]] = {
    "vanguard": {
        "bastion_sword": {
            "name": "Bastion Sword",
            "emoji": "🛡️",
            "description": "Defending prepares a modest retaliatory strike.",
            "effect": "origin_bastion",
            "attack": 3,
        },
        "ashen_maul": {
            "name": "Ashen Maul",
            "emoji": "🔨",
            "description": "Shield Bash deals 8% more damage.",
            "effect": "origin_maul",
            "attack": 4,
        },
        "watch_spear": {
            "name": "Watchman's Spear",
            "emoji": "🔱",
            "description": "Your first basic attack each battle deals 12% more damage.",
            "effect": "origin_spear",
            "attack": 3,
            "luck": 1,
        },
    },
    "shadow": {
        "whisper_knives": {
            "name": "Whisper Knives",
            "emoji": "🗡️",
            "description": "Gain 4% critical chance while the knives are equipped.",
            "effect": "origin_knives",
            "attack": 3,
            "luck": 1,
        },
        "serpent_dirk": {
            "name": "Serpent Dirk",
            "emoji": "🐍",
            "description": "Poison deals one additional damage per turn.",
            "effect": "origin_dirk",
            "attack": 3,
        },
        "lastlight_handbow": {
            "name": "Lastlight Handbow",
            "emoji": "🏹",
            "description": "Basic attacks ignore an additional 10% of armor.",
            "effect": "origin_handbow",
            "attack": 4,
        },
    },
    "arcanist": {
        "ember_focus": {
            "name": "Ember Focus",
            "emoji": "🔥",
            "description": "Burn deals one additional damage per turn.",
            "effect": "origin_ember",
            "attack": 3,
        },
        "frostbound_grimoire": {
            "name": "Frostbound Grimoire",
            "emoji": "❄️",
            "description": "Defending grants 5% stronger protection.",
            "effect": "origin_frost",
            "attack": 2,
            "hp": 6,
        },
        "cracked_hourglass": {
            "name": "Cracked Hourglass",
            "emoji": "⌛",
            "description": "The first ability cast each battle costs one less mana.",
            "effect": "origin_hourglass",
            "attack": 3,
            "luck": 1,
        },
    },
}

REGIONAL_BASES: tuple[dict[str, tuple[str, ...]], ...] = (
    {
        "weapon": ("Lanternblade", "Watch Pike", "Gravedigger's Maul"),
        "armor": ("Lamplighter Coat", "Warren Plate", "Surveyor Harness"),
        "charm": ("Blueflame Wick", "Rat-King Token", "Surveyor Compass"),
    },
    {
        "weapon": ("Thorn Sickle", "Spore Wand", "Cryptfang"),
        "armor": ("Rootbound Mail", "Sporeveil Robes", "Briar Hide"),
        "charm": ("Mourning Seed", "Choir Bell", "Pale Bloom"),
    },
    {
        "weapon": ("Cinder Hammer", "Foundry Glaive", "Memory Brand"),
        "armor": ("Furnace Plate", "Emberweave Mantle", "Chain of Names"),
        "charm": ("Living Coal", "Brass Heart", "Forgemaster Seal"),
    },
    {
        "weapon": ("Court Rapier", "Black-Sun Scepter", "Headsman's Crescent"),
        "armor": ("Nameless Regalia", "Duskguard Plate", "Funeral Velvet"),
        "charm": ("Broken Signet", "Mirror of Oaths", "Ashen Crownlet"),
    },
    {
        "weapon": ("Unwritten Edge", "Voidglass Crook", "Sentence Breaker"),
        "armor": ("Margin Carapace", "Yesterday's Shroud", "Impossible Plate"),
        "charm": ("Starless Eye", "Folded Compass", "Final Word"),
    },
)

EXTRA_PREFIXES: tuple[dict[str, Any], ...] = (
    {"name": "Keen", "attack": 1.14, "luck": 1.08},
    {"name": "Resolute", "defense": 1.15, "hp": 1.1},
    {"name": "Hollow", "attack": 1.1, "hp": 1.12},
    {"name": "Silken", "luck": 1.18, "defense": 1.08},
    {"name": "Cinderbound", "attack": 1.16},
    {"name": "Royal", "all": 1.09},
    {"name": "Starless", "luck": 1.2},
    {"name": "Graveborn", "hp": 1.2},
    {"name": "Runebound", "defense": 1.18},
    {"name": "Impossible", "all": 1.1},
)

EXTRA_SUFFIXES: tuple[dict[str, Any], ...] = (
    {"name": "of the Bulwark", "effect": "brace", "description": "Defending restores a little health."},
    {"name": "of Quickening", "effect": "quickening", "description": "Critical hits may advance a cooldown."},
    {"name": "of Thorns", "effect": "thorns", "description": "Defending retaliates for modest damage."},
    {"name": "of Clarity", "effect": "clarity", "description": "Victories restore a little mana."},
    {"name": "of Ruin", "effect": "ruin", "description": "Basic attacks deal extra armor damage."},
    {"name": "of Mercy", "effect": "mercy", "description": "Potions grant a small temporary guard."},
    {"name": "of Hunger", "effect": "hunger", "description": "Low-health attacks grow stronger."},
    {"name": "of Secrets", "effect": "secrets", "description": "Improves hidden-room and lore discoveries."},
    {"name": "of Echoes", "effect": "echoes", "description": "Abilities may refund one mana."},
    {"name": "of Defiance", "effect": "defiance", "description": "Deal more damage while Cursed."},
)

SUBCLASS_SETS: dict[str, dict[str, Any]] = {
    "citadel": {
        "name": "Walking Citadel",
        "classes": ("vanguard",),
        "subclasses": ("guardian",),
        "two": "+6 DEF and +18 HP",
        "two_stats": {"defense": 6, "hp": 18},
        "three": "Defending restores 3% maximum health.",
    },
    "bloodforged": {
        "name": "Bloodforged Oath",
        "classes": ("vanguard",),
        "subclasses": ("berserker",),
        "two": "+7 ATK",
        "two_stats": {"attack": 7},
        "three": "Bloodrage also grants critical chance.",
    },
    "last_banner": {
        "name": "The Last Banner",
        "classes": ("vanguard",),
        "subclasses": ("warlord",),
        "two": "+4 ATK and +4 DEF",
        "two_stats": {"attack": 4, "defense": 4},
        "three": "Victories restore additional health and mana.",
    },
    "widow": {
        "name": "Widow's Testament",
        "classes": ("shadow",),
        "subclasses": ("assassin",),
        "two": "+5 ATK and +3 LUCK",
        "two_stats": {"attack": 5, "luck": 3},
        "three": "Poison damage is increased by 25%.",
    },
    "mirrorsteel": {
        "name": "Mirrorsteel",
        "classes": ("shadow",),
        "subclasses": ("duelist",),
        "two": "+4 ATK and +4 DEF",
        "two_stats": {"attack": 4, "defense": 4},
        "three": "Riposte chance is increased.",
    },
    "loaded_fate": {
        "name": "Loaded Fate",
        "classes": ("shadow",),
        "subclasses": ("trickster",),
        "two": "+7 LUCK",
        "two_stats": {"luck": 7},
        "three": "Loot rolls gain bad-luck protection.",
    },
    "convergence": {
        "name": "Elemental Convergence",
        "classes": ("arcanist",),
        "subclasses": ("elementalist",),
        "two": "+6 ATK and +12 mana",
        "two_stats": {"attack": 6, "mana": 12},
        "three": "Burn damage is increased by 25%.",
    },
    "grave_covenant": {
        "name": "Grave Covenant",
        "classes": ("arcanist",),
        "subclasses": ("necromancer",),
        "two": "+24 HP and +10 mana",
        "two_stats": {"hp": 24, "mana": 10},
        "three": "Soul Harvest restores additional health.",
    },
    "paradox": {
        "name": "Paradox Regalia",
        "classes": ("arcanist",),
        "subclasses": ("chronomancer",),
        "two": "+18 mana and +3 LUCK",
        "two_stats": {"mana": 18, "luck": 3},
        "three": "Every fourth ability advances another cooldown.",
    },
}

BOSS_RELICS: tuple[dict[str, Any], ...] = (
    {
        "source": "Bellower",
        "name": "Bellower's Silence",
        "slot": "weapon",
        "effect": "silence",
        "description": "Critical hits may cancel the enemy's intention.",
    },
    {
        "source": "Bellower",
        "name": "Resonant Hide",
        "slot": "armor",
        "effect": "resonance",
        "description": "Heavy attacks deal 15% less damage.",
    },
    {
        "source": "Bellower",
        "name": "Echoing Fang",
        "slot": "charm",
        "effect": "battle_mana",
        "description": "The first basic attack restores two mana.",
    },
    {
        "source": "Arachne",
        "name": "Fang of Eight Sorrows",
        "slot": "weapon",
        "effect": "venom_burst",
        "description": "Attacks deal extra damage to poisoned enemies.",
    },
    {
        "source": "Arachne",
        "name": "Widow-Carapace",
        "slot": "armor",
        "effect": "venom_guard",
        "description": "Poison damage taken is halved.",
    },
    {
        "source": "Arachne",
        "name": "Arachne's Promise",
        "slot": "charm",
        "effect": "web",
        "description": "The first enemy attack in each battle always misses.",
    },
    {
        "source": "Hollow",
        "name": "Kingslayer Without a Name",
        "slot": "weapon",
        "effect": "soulrend",
        "description": "Boss victories restore additional health.",
    },
    {
        "source": "Hollow",
        "name": "Crown of No Kingdom",
        "slot": "armor",
        "effect": "crown",
        "description": "Gain attack and defense for every active condition.",
    },
    {
        "source": "Hollow",
        "name": "Royal Seal of Ash",
        "slot": "charm",
        "effect": "royal_fortune",
        "description": "Bosses yield 12% more currency.",
    },
    {
        "source": "Embermaw",
        "name": "Embermaw's Tooth",
        "slot": "weapon",
        "effect": "cinderstrike",
        "description": "Basic critical hits always Burn.",
    },
    {
        "source": "Embermaw",
        "name": "Embermaw's Last Scale",
        "slot": "armor",
        "effect": "rebirth",
        "description": "Survive one fatal hit and erupt in flame.",
    },
    {
        "source": "Embermaw",
        "name": "Heartcoal",
        "slot": "charm",
        "effect": "heartcoal",
        "description": "Burn effects deal additional damage.",
    },
    {
        "source": "Gaoler",
        "name": "Hourbreaker",
        "slot": "weapon",
        "effect": "hourbreaker",
        "description": "Critical hits advance a random cooldown.",
    },
    {
        "source": "Gaoler",
        "name": "Armor of the Held Moment",
        "slot": "armor",
        "effect": "stasis",
        "description": "The first Crushing Blow is partially blocked.",
    },
    {
        "source": "Gaoler",
        "name": "Key to Yesterday",
        "slot": "charm",
        "effect": "clock_key",
        "description": "Every third ability refunds two mana.",
    },
    {
        "source": "Caligo",
        "name": "Eclipse Testament",
        "slot": "weapon",
        "effect": "eclipse",
        "description": "Deal 15% more damage while Cursed.",
    },
    {
        "source": "Caligo",
        "name": "Saint's Unremembered Veil",
        "slot": "armor",
        "effect": "saint_veil",
        "description": "Gain a small chance to evade any attack.",
    },
    {
        "source": "Caligo",
        "name": "Prayer Nobody Heard",
        "slot": "charm",
        "effect": "absolution",
        "description": "Victories shorten negative conditions.",
    },
    {
        "source": "Author",
        "name": "Red Revision",
        "slot": "weapon",
        "effect": "revision",
        "description": "The first attack rewrites the enemy's intention.",
    },
    {
        "source": "Author",
        "name": "Armor Between Lines",
        "slot": "armor",
        "effect": "margin",
        "description": "Fatal damage may leave you at one health once per floor.",
    },
    {
        "source": "Author",
        "name": "The Unwritten Key",
        "slot": "charm",
        "effect": "key",
        "description": "Narrative tests roll twice and take the better result.",
    },
)

CONSUMABLES: dict[str, dict[str, Any]] = {
    "lantern_tonic": {
        "name": "Lantern Tonic",
        "emoji": "🧪",
        "region": 0,
        "effect": "heal",
        "power": 28,
        "description": "Restore health outside or during battle.",
    },
    "smoke_vial": {
        "name": "Smoke Vial",
        "emoji": "💨",
        "region": 0,
        "effect": "evade",
        "power": 1,
        "description": "Evade the next enemy attack.",
    },
    "iron_oil": {
        "name": "Iron Oil",
        "emoji": "⚔️",
        "region": 0,
        "effect": "attack",
        "power": 3,
        "description": "Gain attack for the current battle.",
    },
    "spore_antidote": {
        "name": "Spore Antidote",
        "emoji": "🌿",
        "region": 1,
        "effect": "cleanse",
        "power": 1,
        "description": "Remove Poison and Curse.",
    },
    "dreamcap_draught": {
        "name": "Dreamcap Draught",
        "emoji": "🍄",
        "region": 1,
        "effect": "mana",
        "power": 18,
        "description": "Restore mana.",
    },
    "thorn_bomb": {
        "name": "Thorn Bomb",
        "emoji": "🌹",
        "region": 1,
        "effect": "damage",
        "power": 30,
        "description": "Damage the current enemy.",
    },
    "cinder_flask": {
        "name": "Cinder Flask",
        "emoji": "🔥",
        "region": 2,
        "effect": "burn",
        "power": 4,
        "description": "Burn the current enemy.",
    },
    "forge_salve": {
        "name": "Forge Salve",
        "emoji": "🩹",
        "region": 2,
        "effect": "heal",
        "power": 48,
        "description": "Restore substantial health.",
    },
    "sundering_charge": {
        "name": "Sundering Charge",
        "emoji": "💣",
        "region": 2,
        "effect": "sunder",
        "power": 25,
        "description": "Damage and break enemy armor.",
    },
    "courtly_elixir": {
        "name": "Courtly Elixir",
        "emoji": "👑",
        "region": 3,
        "effect": "guard",
        "power": 45,
        "description": "Gain a strong guard for the next attack.",
    },
    "mirror_shard": {
        "name": "Mirror Shard",
        "emoji": "🪞",
        "region": 3,
        "effect": "reroll",
        "power": 1,
        "description": "Rewrite the enemy's intention.",
    },
    "royal_incense": {
        "name": "Royal Incense",
        "emoji": "🌑",
        "region": 3,
        "effect": "luck",
        "power": 5,
        "description": "Gain Luck for the current battle.",
    },
    "voidglass_bomb": {
        "name": "Voidglass Bomb",
        "emoji": "🔷",
        "region": 4,
        "effect": "damage",
        "power": 65,
        "description": "Deal heavy armor-piercing damage.",
    },
    "folded_moment": {
        "name": "Folded Moment",
        "emoji": "⏳",
        "region": 4,
        "effect": "cooldown",
        "power": 2,
        "description": "Advance all ability cooldowns.",
    },
    "margin_scroll": {
        "name": "Margin Scroll",
        "emoji": "📜",
        "region": 4,
        "effect": "escape",
        "power": 1,
        "description": "Guarantee escape from a non-boss battle.",
    },
}

RECIPES: dict[str, dict[str, Any]] = {
    "lanternsteel": {"name": "Lanternsteel Pattern", "slot": "weapon", "region": 0, "effect": "silence"},
    "sporeward": {"name": "Sporeward Pattern", "slot": "armor", "region": 1, "effect": "venom_guard"},
    "emberbrand": {"name": "Emberbrand Pattern", "slot": "weapon", "region": 2, "effect": "cinderstrike"},
    "court_seal": {"name": "Court-Seal Pattern", "slot": "charm", "region": 3, "effect": "royal_fortune"},
    "void_revision": {"name": "Void Revision Pattern", "slot": "charm", "region": 4, "effect": "revision"},
}

MINIBOSSES: tuple[dict[str, Any], ...] = (
    {"name": "The Lantern Butcher", "emoji": "🪓", "region": 0, "hp": 1.65, "attack": 1.2, "defense": 1.1},
    {"name": "Mother Mycelia", "emoji": "🍄", "region": 1, "hp": 1.75, "attack": 1.15, "defense": 1.15},
    {"name": "The Brass Confessor", "emoji": "⚙️", "region": 2, "hp": 1.6, "attack": 1.3, "defense": 1.2},
    {"name": "The Last Courtier", "emoji": "🎭", "region": 3, "hp": 1.7, "attack": 1.25, "defense": 1.2},
    {"name": "The Redacted Beast", "emoji": "🖋️", "region": 4, "hp": 1.85, "attack": 1.3, "defense": 1.15},
)

FLOOR_MUTATORS: tuple[dict[str, Any], ...] = (
    {"key": "darkness", "name": "Lightless", "description": "Enemies are harder to evade; hidden rooms are more common."},
    {"key": "flooded", "name": "Flooded", "description": "Enemy attack is reduced, but healing is weaker."},
    {"key": "unstable", "name": "Unstable Magic", "description": "Abilities and enemy intentions are more volatile."},
    {"key": "hunted", "name": "Hunted", "description": "Minibosses are more common and rewards are richer."},
    {"key": "hollow", "name": "Hollow Air", "description": "Mana recovery is reduced while treasure improves."},
)

STORY_RELICS: dict[str, dict[str, str]] = {
    "truth": {"name": "The Unshuttered Lantern", "description": "Its flame exposes every comforting omission."},
    "mercy": {"name": "The Star's Warm Fragment", "description": "A reminder that compassion survived the Deep."},
    "power": {"name": "The Star's Burning Fragment", "description": "It beats like a second, ambitious heart."},
    "seal": {"name": "The Star's Quiet Cocoon", "description": "Something patient dreams behind its silver shell."},
    "free": {"name": "Empty Celestial Cage", "description": "Freedom left an outline behind."},
    "harvest": {"name": "Pressed Memory Ingot", "description": "It remembers every shape except its own."},
    "destroy": {"name": "Hammer of the Last Command", "description": "The Foundry still flinches from it."},
    "preserve": {"name": "Unspent Royal Name", "description": "A kingdom waits silently inside one word."},
    "ignite": {"name": "Fifth-Bell Clapper", "description": "It rings only in dreams."},
    "speak": {"name": "The King's True Name", "description": "Reading it changes the reader."},
    "erase": {"name": "Blank Royal Epitaph", "description": "No ghost can remember who lies beneath it."},
    "inherit": {"name": "Living Hollow Crown", "description": "It is warm because it is listening."},
    "descend": {"name": "Warden's First Key", "description": "It opens a stair that only exists for its keeper."},
    "reveal": {"name": "The Final Open Page", "description": "Lastlight's future writes itself where all can see."},
}
