"""Gameplay service modules used by DeepDelve."""

from .armory import (
    boss_relic_for,
    comparison_line,
    create_starter_item,
    item_power,
    recipe_for_region,
    roll_consumable,
    should_auto_dismantle,
    starter_options,
    use_consumable,
)
from .atlas import (
    abandon_dungeon,
    advance_dungeon,
    atlas_locations,
    ensure_atlas,
    enter_dungeon,
    record_dungeon_victory,
    resolve_dungeon_choice,
)
from .campaign import advance_campaign, campaign_bonuses, campaign_scene, campaign_state, chapter_available
from .combat import ensure_enemy_intent, intent_description, roll_enemy_intent
from .commissions import (
    accept_commission,
    commission_board,
    ensure_commissions,
    progress_commission,
    research_recipe,
)
from .companions import active_companion, companion_bonuses, grant_companion_xp, unlock_companions
from .content_registry import content_counts, validate_content
from .dungeon_depth import (
    apply_miniboss,
    create_rumor,
    ending_recap,
    floor_mutator,
    progress_rumor,
    record_bestiary_kill,
    region_index,
)
from .economy import TARGET_SINK_RANGE, economy_release_gate, equivalent_rewards, reward_budget, simulate_active_economy
from .endgame import current_season, daily_dungeon, restore_challenge_origin, scaled_daily_floor
from .items import (
    ENCHANTMENTS,
    apply_advanced_itemization,
    apply_item_upgrade,
    dismantle_rewards,
    enchant_cost,
    equipment_effects,
    equipment_set_bonuses,
    item_detail,
    item_effects,
    item_sale_value,
    upgrade_cost,
    upgrade_stat_changes,
)
from .legacy import (
    accept_oath,
    advance_redemption,
    backfill_historical_resolve,
    begin_redemption,
    change_faction_reputation,
    ensure_legacy,
    equip_tenets,
    grant_resolve,
    oath_board,
    progress_oath,
    tenet_available,
    tenet_effects,
    unlock_tenet,
    use_faction_service,
)
from .living_campaign import ENDINGS, advance_living_campaign, ensure_living_campaign, living_campaign_view
from .morality import (
    ensure_morality,
    moral_power,
    morality_path,
    npc_moral_reaction,
    origin_morality,
    record_campaign_deed,
    record_choice_deed,
    use_moral_power,
)
from .nemesis import create_nemesis, defeat_nemesis, ensure_nemeses, record_nemesis_escape
from .professions import gather, grant_profession_xp, profession_level, profession_rank
from .progression import (
    available_abilities,
    progression_bonuses,
    refresh_titles,
    subclass_options,
)
from .quests import (
    QUESTS,
    accept_quest,
    available_quests,
    ensure_quests,
    expire_quests,
    fail_quest,
    perform_skill_check,
    progress_quests,
    requirement_status,
    resolve_quest,
    skill_check_chance,
)
from .relationships import (
    change_relationship,
    ensure_relationships,
    generate_mail,
    give_gift,
    relationship_level,
    request_favor,
    world_echoes,
)
from .sanctum import SANCTUM_ROOMS, ensure_sanctum, sanctum_upgrade_cost, upgrade_sanctum
from .season_archive import (
    advance_season_chapter,
    begin_season_chapter,
    ensure_season_story,
    season_chapter_status,
)
from .social import arena_power, guild_perks, party_bonus, short_code
from .story import npc_progress
from .world import active_world_event, town_bonuses, upgrade_building

__all__ = [
    "ENCHANTMENTS",
    "ENDINGS",
    "QUESTS",
    "SANCTUM_ROOMS",
    "TARGET_SINK_RANGE",
    "abandon_dungeon",
    "accept_commission",
    "accept_oath",
    "accept_quest",
    "active_companion",
    "active_world_event",
    "advance_campaign",
    "advance_dungeon",
    "advance_living_campaign",
    "advance_redemption",
    "advance_season_chapter",
    "apply_advanced_itemization",
    "apply_item_upgrade",
    "apply_miniboss",
    "arena_power",
    "atlas_locations",
    "available_abilities",
    "available_quests",
    "backfill_historical_resolve",
    "begin_redemption",
    "begin_season_chapter",
    "boss_relic_for",
    "campaign_bonuses",
    "campaign_scene",
    "campaign_state",
    "change_faction_reputation",
    "change_relationship",
    "chapter_available",
    "commission_board",
    "companion_bonuses",
    "comparison_line",
    "content_counts",
    "create_nemesis",
    "create_rumor",
    "create_starter_item",
    "current_season",
    "daily_dungeon",
    "defeat_nemesis",
    "dismantle_rewards",
    "economy_release_gate",
    "enchant_cost",
    "ending_recap",
    "ensure_atlas",
    "ensure_commissions",
    "ensure_enemy_intent",
    "ensure_legacy",
    "ensure_living_campaign",
    "ensure_morality",
    "ensure_nemeses",
    "ensure_quests",
    "ensure_relationships",
    "ensure_sanctum",
    "ensure_season_story",
    "enter_dungeon",
    "equip_tenets",
    "equipment_effects",
    "equipment_set_bonuses",
    "equivalent_rewards",
    "expire_quests",
    "fail_quest",
    "floor_mutator",
    "gather",
    "generate_mail",
    "give_gift",
    "grant_companion_xp",
    "grant_profession_xp",
    "grant_resolve",
    "guild_perks",
    "intent_description",
    "item_detail",
    "item_effects",
    "item_power",
    "item_sale_value",
    "living_campaign_view",
    "moral_power",
    "morality_path",
    "npc_moral_reaction",
    "npc_progress",
    "oath_board",
    "origin_morality",
    "party_bonus",
    "perform_skill_check",
    "profession_level",
    "profession_rank",
    "progress_commission",
    "progress_oath",
    "progress_quests",
    "progress_rumor",
    "progression_bonuses",
    "recipe_for_region",
    "record_bestiary_kill",
    "record_campaign_deed",
    "record_choice_deed",
    "record_dungeon_victory",
    "record_nemesis_escape",
    "refresh_titles",
    "region_index",
    "relationship_level",
    "request_favor",
    "requirement_status",
    "research_recipe",
    "resolve_dungeon_choice",
    "resolve_quest",
    "restore_challenge_origin",
    "reward_budget",
    "roll_consumable",
    "roll_enemy_intent",
    "sanctum_upgrade_cost",
    "scaled_daily_floor",
    "season_chapter_status",
    "short_code",
    "should_auto_dismantle",
    "simulate_active_economy",
    "skill_check_chance",
    "starter_options",
    "subclass_options",
    "tenet_available",
    "tenet_effects",
    "town_bonuses",
    "unlock_companions",
    "unlock_tenet",
    "upgrade_building",
    "upgrade_cost",
    "upgrade_sanctum",
    "upgrade_stat_changes",
    "use_consumable",
    "use_faction_service",
    "use_moral_power",
    "validate_content",
    "world_echoes",
]
